# name: EAS Build

# on:
#   workflow_dispatch:
#   push:
#     branches: [main]

# jobs:
#   build:
#     name: Build Dev Client + Internal
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - name: Setup Expo and EAS
#         uses: expo/expo-github-action@v8
#         with:
#           eas-version: latest
#           token: ${{ secrets.EXPO_TOKEN }}

#       - name: Install dependencies
#         run: npm ci

#       - name: Build Development Client
#         run: eas build --platform ios --profile development --non-interactive --no-wait

#       - name: Build Internal Preview
#         run: eas build --platform ios --profile preview --non-interactive --no-wait
